const API_BASE_URL = "http://localhost:3500";

const API_ENDPOINT_FOR_PROMPTS = `${API_BASE_URL}/prompt`;

const API_ENDPOINT_FOR_MESSAGE = `${API_BASE_URL}/message`;

const API_ENDPOINT_FOR_USER = `${API_BASE_URL}/user`;

const API_ENDPOINT_FOR_CONVERSATION = `${API_BASE_URL}/conversation`;

export {
  API_BASE_URL,
  API_ENDPOINT_FOR_PROMPTS,
  API_ENDPOINT_FOR_MESSAGE,
  API_ENDPOINT_FOR_USER,
  API_ENDPOINT_FOR_CONVERSATION,
};
