const API_BASE_URL = "https://ai-interviewer-backend.vercel.app";

const API_ENDPOINT_FOR_PROMPTS = `${API_BASE_URL}/prompt`;

const API_ENDPOINT_FOR_MESSAGE = `${API_BASE_URL}/message`;

const API_ENDPOINT_FOR_USER = `${API_BASE_URL}/user`;

const API_ENDPOINT_FOR_CONVERSATION = `${API_BASE_URL}/conversation`;

const API_ENDPOINT_FOR_JOB = `${API_BASE_URL}/job`;

const API_ENDPOINT_FOR_SKILL = `${API_BASE_URL}/skill`;

export {
  API_BASE_URL,
  API_ENDPOINT_FOR_PROMPTS,
  API_ENDPOINT_FOR_MESSAGE,
  API_ENDPOINT_FOR_USER,
  API_ENDPOINT_FOR_CONVERSATION,
  API_ENDPOINT_FOR_JOB,
  API_ENDPOINT_FOR_SKILL,
};
